import nodemailer from 'nodemailer';

// Create SMTP transporter using environment variables
// Supports Gmail, Outlook, or any SMTP provider
function createTransporter() {
  const host = process.env.SMTP_HOST || 'smtp.gmail.com';
  const port = Number(process.env.SMTP_PORT) || 587;
  const user = process.env.SMTP_USER || '';
  const pass = process.env.SMTP_PASS || '';

  if (!user || !pass || user.includes('your_')) {
    return null;
  }

  return nodemailer.createTransport({
    host,
    port,
    secure: port === 465,
    auth: { user, pass },
  });
}

export async function sendJobPDF(email: string, pdfBuffer: Buffer, jobName: string) {
  const transporter = createTransporter();

  if (!transporter) {
    console.warn("SMTP credentials not configured. Skipping email.");
    return { success: false, error: 'SMTP not configured' };
  }

  try {
    const info = await transporter.sendMail({
      from: `"Roof Auto AI" <${process.env.SMTP_USER}>`,
      to: email,
      subject: `Materials Order & Crew Summary - ${jobName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #1e40af;">Roof Auto AI</h1>
          <h2>Materials Order & Crew Summary</h2>
          <p>Hi,</p>
          <p>Please find attached the automated materials order and crew summary for <strong>${jobName}</strong>.</p>
          <p>This document was generated by Claude AI and contains the calculated material quantities based on the uploaded Eagle View report and supporting documents.</p>
          <hr style="border-color: #e2e8f0;" />
          <p style="color: #64748b; font-size: 12px;">Generated by Roof Auto AI — Reliable Exteriors Group</p>
        </div>
      `,
      attachments: [
        {
          filename: `${jobName.replace(/\s+/g, '_')}_Materials_Order.pdf`,
          content: pdfBuffer,
          contentType: 'application/pdf',
        },
      ],
    });

    console.log("Email sent successfully to:", email, "MessageID:", info.messageId);
    return { success: true, data: { messageId: info.messageId } };
  } catch (error: any) {
    console.error('Error sending email:', error?.message || error);
    return { success: false, error: error?.message || 'Unknown email error' };
  }
}
