import { Resend } from 'resend';

const resend = process.env.RESEND_API_KEY && !process.env.RESEND_API_KEY.includes('your_')
  ? new Resend(process.env.RESEND_API_KEY) 
  : null;

export async function sendJobPDF(email: string, pdfBuffer: Buffer, jobName: string) {
  if (!resend) {
    console.warn("Resend API Key missing or placeholder. Skipping email.");
    return { success: false, error: 'Resend API Key not configured' };
  }

  try {
    const data = await resend.emails.send({
      from: 'Roof Auto <onboarding@resend.dev>',
      to: [email],
      subject: `Materials Order & Crew Summary - ${jobName}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #1e40af;">Roof Auto AI</h1>
          <h2>Materials Order & Crew Summary</h2>
          <p>Hi,</p>
          <p>Please find attached the automated materials order and crew summary for <strong>${jobName}</strong>.</p>
          <p>This document was generated by Claude AI and contains the calculated material quantities based on the uploaded Eagle View report and supporting documents.</p>
          <hr style="border-color: #e2e8f0;" />
          <p style="color: #64748b; font-size: 12px;">Generated by Roof Auto AI — Reliable Exteriors Group</p>
        </div>
      `,
      attachments: [
        {
          filename: `${jobName.replace(/\s+/g, '_')}_Materials_Order.pdf`,
          content: pdfBuffer.toString('base64'),
          contentType: 'application/pdf',
        },
      ],
    });
    console.log("Email sent successfully to:", email);
    return { success: true, data };
  } catch (error: any) {
    console.error('Error sending email:', error?.message || error);
    return { success: false, error: error?.message || 'Unknown email error' };
  }
}
